version: '3.3'

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: goopnigoop/elasticsearch:latest
    build:
      context: ./elk/elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  filebeat:
    hostname: filebeat
    container_name: filebeat
    image: goopnigoop/filebeat:latest
    build:
      context: ./elk/filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (read only) :
      - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./wait-for-it.sh:/usr/share/filebeat/wait-for-it.sh
    command: bash -c "wait-for-it.sh --timeout=60 elasticsearch:9200 && filebeat"
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: goopnigoop/kibana:latest
    build:
      context: ./elk/kibana
      dockerfile: Dockerfile
    volumes:
      - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
    ports:
      - 5601:5601
    command: bash -c "wait-for-it.sh --timeout=60 elasticsearch:9200 && kibana"
    depends_on:
      - elasticsearch

  logstash:
    hostname: logstash
    image: goopnigoop/logstash:latest
    container_name: logstash
    build:
      context: ./elk/logstash
      dockerfile: Dockerfile
    ports:
      - 5044:5044
    environment:
      LOG_LEVEL: error
    volumes:
      - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
      - ./elk/logstash/pipeline/:/usr/share/logstash/pipeline/
    command: bash -c "wait-for-it.sh --timeout=60 elasticsearch:9200 && logstash -f /usr/share/logstash/pipeline/logstash.conf"
    depends_on:
      - elasticsearch

  metadata:
    image: goopnigoop/metadata:latest
    container_name: metadata
    build:
      context: ./metadata
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
      - '5009:5005'
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - metadata


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - prometheus

networks:
  default:
    driver: bridge
